version: '3'
services:
  web:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails-graphql
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle_cache
      - GEM_HOME=/bundle_cache
      - GEM_PATH=/bundle_cache
  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

volumes:
  bundle_cache:
